### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by altynexpress** [ramusus/django-instagram-api#5]
Здравствуйте,

я указал все настройки которые нужно было добавить, но User.remote.fetch не работает
OAUTH_TOKENS_HISTORY = True
OAUTH_TOKENS_INSTAGRAM_CLIENT_ID = '**_'
OAUTH_TOKENS_INSTAGRAM_CLIENT_SECRET = '**_'
OAUTH_TOKENS_INSTAGRAM_USERNAME = '**_'
OAUTH_TOKENS_INSTAGRAM_PASSWORD = '**_'

INSTALLED_APPS = (
    ***,
    'oauth_tokens',
    'm2m_history',
    'taggit',
    'instagram_api',
)

Можете пожалуйста помочь в настройках. Мне очень интересен Ваша библиотека.

**Comment by ramusus** [comment]
Возможно ваше приложение находится в sandbox ?

**Comment by altynexpress** [comment]
нет точно не в sandbox, я создал свое приложение до появления sandbox.
может у Вас есть приложение sample какой нибудь, чтобы я мог научится пользоваться Вашей библиотекой.

**Comment by altynexpress** [comment]
а что нужно указать для OAUTH_TOKENS_API_CALL_CONTEXT?

**Comment by altynexpress** [comment]
OAUTH_TOKENS_API_CALL_CONTEXT = {'instagram': {'token': '*****************'}}
предоставил вручную токен, заработало.
Но не могу понять почему он сам не может запросить токены? :(

**Comment by altynexpress** [comment]
кстати кажется python-social-auth не работает в апи

**Comment by ramusus** [comment]
попробуйте запустить тесты приложения oauth_tokens там есть тест на получение токена для instagram

**Comment by altynexpress** [comment]
все три теста прошли успешно.

**Comment by ramusus** [comment]
но если заменить на ваши логин и пароль, то не проходят? значит нужно дебажить

**Comment by altynexpress** [comment]
There is no any form in response

Request Method:     GET
Request URL:    http://localhost:8515/
Django Version:     1.7.10
Exception Type:     Exception
Exception Value:  
There is no any form in response
Exception Location:     /home/mayer/projects/ENV/local/lib/python2.7/site-packages/oauth_tokens/base.py in get_form_from_bs_content, line 91
Python Executable:  /home/mayer/projects/ENV/bin/python
Python Version:     2.7.10

**Comment by altynexpress** [comment]
Можно ли не указывая пароль с логином, использовать только OAUTH_TOKENS_INSTAGRAM_CLIENT_ID, OAUTH_TOKENS_INSTAGRAM_CLIENT_SECRET?
Я хочу чтобы пользователь сам авторизовался, и я мог использовать его токены.

**Comment by ramusus** [comment]
В этом случае задайте 
OAUTH_TOKENS_API_CALL_CONTEXT = {'instagram': {'token': ....}} и можно не указывать логин и пароль

**Comment by altynexpress** [comment]
Я не так изложил суть. 
в instagram api есть 2 способа аутентификации:
1) Server-side (Explicit) Flow
2) Client-Side (Implicit) Authentication

Вы похоже используете только 2-ой вариант, мне нужно 1-ый вариант.
Я не хочу хранить пароли пользователей. и 1-ый вариант более безопасный.

Кстати я разобрался со своей проблемой, у меня в безопасности был заблокирован 2-ой способ аутентификации.

**Comment by ramusus** [comment]
да, мы используем 2 способ.
Обратите внимание на библиотеку python-social-auth. Там есть бэкенд для аутентификации, возможно Вам подойдет. тикет закрываю?

**Comment by altynexpress** [comment]
ой сорри, да конечно, я не думал что это будет как тикет.
